### ISSUE TITLE
Get info from homepage?

### ISSUE THREAD

**Issue by azertypow** [azertypow/site-master-head#16]
<img width="729" alt="capture d ecran 2018-11-19 a 09 43 00" src="https://user-images.githubusercontent.com/12177073/48695707-202fb800-ebe0-11e8-9c36-a458d330ced4.png">

**Comment by qwertzuiop13** [comment]
Titre de la page
Texte d'introduction de la page home (FR/EN)

Texte de description de la section events (FR/EN)
Texte de description de la section workshop (FR/EN)
Texte de description de la section séminaire (FR/EN)

Il n'y a pas de titre dispo pour ces trois sections, je me suis dit que tu les mettrais en dur.

**Comment by azertypow** [comment]
ok pas compris, c'est tout bon alors
